export const daysInMonthDict = {
    1: 31,
    2: 28,
    3: 31,
    4: 30,
    5: 31,
    6: 30,
    7: 31,
    8: 31,
    9: 30,
    10: 31,
    11: 30,
    12: 31,
};
export const monthNames = {
    1: "January",
    2: "February",
    3: "March",
    4: "April",
    5: "May",
    6: "June",
    7: "July",
    8: "August",
    9: "September",
    10: "October",
    11: "November",
    12: "December",
};

export const monthNamesAltered = {
    1: "January",
    2: "February",
    3: "March",
    4: "April",
    5: "May",
    6: "June",
    7: "July",
    8: "August",
    9: "September",
    10: "October",
    11: "November",
    12: "December",
};

// export const monthNames = {
//     1: "Styczeń",
//     2: "Luty",
//     3: "Marzec",
//     4: "Kwiecień",
//     5: "Maj",
//     6: "Czerwiec",
//     7: "Lipiec",
//     8: "Sierpień",
//     9: "Wrzesień",
//     10: "Październik",
//     11: "Listopad",
//     12: "Grudzień",
// };

// export const monthNamesAltered = {
//     1: "Stycznia",
//     2: "Lutego",
//     3: "Marca",
//     4: "Kwietnia",
//     5: "Maja",
//     6: "Czerwca",
//     7: "Lipca",
//     8: "Sierpnia",
//     9: "Września",
//     10: "Października",
//     11: "Listopada",
//     12: "Grudnia",
// };
